[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Headers di sicurezza generali
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers per file JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers per file CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers per file HTML
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers per manifest
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# Redirect per la landing page
[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

# Redirect per l'app (SPA)
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

# Redirect per tutte le altre rotte dell'app
[[redirects]]
  from = "/auth"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/onboarding"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/meals"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/progress"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/history"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/recipes"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/index.html"
  status = 200

# Fallback per tutte le altre rotte (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
